# docker-compose.yml
# Define the version of the Compose file format
version: "3.9"

# Define the services
services:
  # The app service
  app:
    # Build the image from the Dockerfile
    build: .
    # Map port 3000 on the host to port 3000 in the container
    ports:
      - "3000:3000"
